import {
  Branch,
  Product,
  BranchInventory,
  Supplier,
  Staff,
  Purchase,
  PurchaseBill,
  PurchaseAllocationRecord,
  Sale,
  StockMovement,
  AttendanceRecord,
  SalaryRecord,
  NotificationItem,
  AppSettings,
  User,
} from '../src/types.ts';

export const INITIAL_SETTINGS: AppSettings = {
  businessName: 'PET WORLD',
  tagline: 'Premium Multi-Branch Pet Care & Retail Chain',
  headOfficeAddress: 'Pet World Tower, Suite 402, Nariman Point, Mumbai, MH 400021',
  headOfficePhone: '+91 22 4589 8800',
  gstin: '27AABCP1924M1Z5',
  invoicePrefix: 'PW-SAL-',
  thermalWidth: '80mm',
  defaultTaxRate: 18,
  currencySymbol: '₹',
  currencyCode: 'INR',
  lowStockDefaultThreshold: 10,
  receiptFooter: 'Thank you for caring for your furry friends! Visit us at www.petworld.co.in | No exchange without bill',
  paymentMethods: ['CASH', 'UPI', 'CARD', 'SPLIT'],
};

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'branch-1',
    code: 'B01',
    name: 'Pet World Downtown Flagship',
    address: '14/B, Colaba Causeway, Near Regal Cinema',
    city: 'Mumbai',
    phone: '+91 22 2202 1144',
    email: 'colaba@petworld.co.in',
    managerName: 'Rajesh Sharma',
    status: 'ACTIVE',
    openingDate: '2021-03-15',
    taxRate: 18,
  },
  {
    id: 'branch-2',
    code: 'B02',
    name: 'Pet World Westside Mall',
    address: 'Ground Floor, Galleria Arcade, Linking Road, Bandra West',
    city: 'Mumbai',
    phone: '+91 22 2640 8822',
    email: 'bandra@petworld.co.in',
    managerName: 'Priya Mehra',
    status: 'ACTIVE',
    openingDate: '2021-09-10',
    taxRate: 18,
  },
  {
    id: 'branch-3',
    code: 'B03',
    name: 'Pet World Suburban Plaza',
    address: 'Unit 4, Western Heights, Chakala, Andheri East',
    city: 'Mumbai',
    phone: '+91 22 2838 5599',
    email: 'andheri@petworld.co.in',
    managerName: 'Amit Verma',
    status: 'ACTIVE',
    openingDate: '2022-04-01',
    taxRate: 18,
  },
  {
    id: 'branch-4',
    code: 'B04',
    name: 'Pet World Green Valley',
    address: 'Hiranandani Gardens, Central Avenue, Powai',
    city: 'Mumbai',
    phone: '+91 22 2570 3311',
    email: 'powai@petworld.co.in',
    managerName: 'Neha Deshmukh',
    status: 'ACTIVE',
    openingDate: '2022-11-20',
    taxRate: 18,
  },
  {
    id: 'branch-5',
    code: 'B05',
    name: 'Pet World Coastal Bay',
    address: '7 Juhu Tara Road, Opposite Sea Princess Hotel, Juhu',
    city: 'Mumbai',
    phone: '+91 22 2618 9944',
    email: 'juhu@petworld.co.in',
    managerName: 'Karan Malhotra',
    status: 'ACTIVE',
    openingDate: '2023-06-12',
    taxRate: 18,
  },
  {
    id: 'branch-6',
    code: 'B06',
    name: 'Pet World Express Hub',
    address: 'Shop 12-14, Viviana Boulevard, Eastern Express Highway, Thane West',
    city: 'Thane',
    phone: '+91 22 2544 6677',
    email: 'thane@petworld.co.in',
    managerName: 'Sunita Patil',
    status: 'ACTIVE',
    openingDate: '2024-01-18',
    taxRate: 18,
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-1',
    name: 'Royal Canin India Pvt Ltd',
    contactPerson: 'Sandeep Ghosh',
    phone: '+91 98201 44552',
    email: 'orders@royalcanin.in',
    address: 'B-601, Nesco IT Park, Goregaon East, Mumbai',
    gstin: '27AABCR4450E1Z1',
  },
  {
    id: 'sup-2',
    name: 'Mars Petcare India (Pedigree / Whiskas)',
    contactPerson: 'Ananya Roy',
    phone: '+91 98334 11220',
    email: 'wholesale@marspetcare.in',
    address: 'DLF Cyber City, Tower 10, Gurugram / Mumbai Depot',
    gstin: '27AACCM2918K1ZX',
  },
  {
    id: 'sup-3',
    name: 'Drools Pet Food Pvt Ltd',
    contactPerson: 'Manoj Tiwari',
    phone: '+91 99112 88440',
    email: 'distributor@drools.in',
    address: 'IB Group Complex, Rajnandgaon & Bhiwandi Logistics Hub',
    gstin: '27AABCD6710F1Z4',
  },
  {
    id: 'sup-4',
    name: 'Pet Passion Import & Distribution Hub',
    contactPerson: 'Farhan Merchant',
    phone: '+91 98200 99441',
    email: 'sales@petpassion.co.in',
    address: 'Gala 10, Mittal Industrial Estate, Andheri Kurla Rd, Mumbai',
    gstin: '27AAECP1144Q1Z8',
  },
  {
    id: 'sup-5',
    name: 'Aquaria World & Exotic Marine',
    contactPerson: 'Victor Fernandes',
    phone: '+91 97690 33221',
    email: 'contact@aquariaworld.in',
    address: 'Shop 4, Crawford Market Marine Annexe, Mumbai',
    gstin: '27AAGFA9812M1Z2',
  },
  {
    id: 'sup-6',
    name: 'VetCare India Pharmaceuticals',
    contactPerson: 'Dr. Ramesh Nair',
    phone: '+91 98450 77112',
    email: 'supply@vetcarepharma.in',
    address: '22 Peenya Industrial Area, Bengaluru / Mumbai CFA',
    gstin: '27AABCV1290P1Z6',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // DOG FOOD (12 items)
  {
    id: 'prod-001',
    sku: 'DF-RC-001',
    barcode: '89010010001',
    name: 'Royal Canin Maxi Adult Dog Food 15kg',
    category: 'Dog Food',
    brand: 'Royal Canin',
    unit: 'packet',
    purchasePrice: 6200,
    sellingPrice: 7990,
    mrp: 8400,
    taxPercent: 18,
    minStockLevel: 5,
    reorderLevel: 10,
    supplierId: 'sup-1',
    supplierName: 'Royal Canin India Pvt Ltd',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-002',
    sku: 'DF-RC-002',
    barcode: '89010010002',
    name: 'Royal Canin Mini Adult Dog Food 4kg',
    category: 'Dog Food',
    brand: 'Royal Canin',
    unit: 'packet',
    purchasePrice: 2250,
    sellingPrice: 2890,
    mrp: 3100,
    taxPercent: 18,
    minStockLevel: 8,
    reorderLevel: 15,
    supplierId: 'sup-1',
    supplierName: 'Royal Canin India Pvt Ltd',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-003',
    sku: 'DF-PED-003',
    barcode: '89010010003',
    name: 'Pedigree Adult Chicken & Vegetables 10kg',
    category: 'Dog Food',
    brand: 'Pedigree',
    unit: 'packet',
    purchasePrice: 1650,
    sellingPrice: 2150,
    mrp: 2300,
    taxPercent: 18,
    minStockLevel: 10,
    reorderLevel: 20,
    supplierId: 'sup-2',
    supplierName: 'Mars Petcare India',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-004',
    sku: 'DF-PED-004',
    barcode: '89010010004',
    name: 'Pedigree Pro Starter Mother & Pup 3kg',
    category: 'Dog Food',
    brand: 'Pedigree',
    unit: 'packet',
    purchasePrice: 1100,
    sellingPrice: 1450,
    mrp: 1550,
    taxPercent: 18,
    minStockLevel: 6,
    reorderLevel: 12,
    supplierId: 'sup-2',
    supplierName: 'Mars Petcare India',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-005',
    sku: 'DF-FAR-005',
    barcode: '89010010005',
    name: 'Farmina N&D Pumpkin Lamb & Blueberry 12kg',
    category: 'Dog Food',
    brand: 'Farmina',
    unit: 'packet',
    purchasePrice: 6900,
    sellingPrice: 8850,
    mrp: 9400,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-006',
    sku: 'DF-HIL-006',
    barcode: '89010010006',
    name: "Hill's Science Diet Canine Adult 12kg",
    category: 'Dog Food',
    brand: "Hill's",
    unit: 'packet',
    purchasePrice: 5800,
    sellingPrice: 7400,
    mrp: 7900,
    taxPercent: 18,
    minStockLevel: 5,
    reorderLevel: 10,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-007',
    sku: 'DF-DRO-007',
    barcode: '89010010007',
    name: 'Drools Focus Puppy Super Premium 15kg',
    category: 'Dog Food',
    brand: 'Drools',
    unit: 'packet',
    purchasePrice: 3800,
    sellingPrice: 4950,
    mrp: 5300,
    taxPercent: 18,
    minStockLevel: 6,
    reorderLevel: 12,
    supplierId: 'sup-3',
    supplierName: 'Drools Pet Food Pvt Ltd',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-008',
    sku: 'DF-ORI-008',
    barcode: '89010010008',
    name: 'Orijen Original Grain-Free Dog 11.4kg',
    category: 'Dog Food',
    brand: 'Orijen',
    unit: 'packet',
    purchasePrice: 8900,
    sellingPrice: 11400,
    mrp: 12000,
    taxPercent: 18,
    minStockLevel: 3,
    reorderLevel: 6,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-009',
    sku: 'DF-ACA-009',
    barcode: '89010010009',
    name: 'Acana Grasslands Heritage Dog 6kg',
    category: 'Dog Food',
    brand: 'Acana',
    unit: 'packet',
    purchasePrice: 4600,
    sellingPrice: 5900,
    mrp: 6300,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-010',
    sku: 'DF-PUR-010',
    barcode: '89010010010',
    name: 'Purina Pro Plan Adult Medium Chicken 14kg',
    category: 'Dog Food',
    brand: 'Purina',
    unit: 'packet',
    purchasePrice: 5500,
    sellingPrice: 6990,
    mrp: 7500,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-011',
    sku: 'DF-TOW-011',
    barcode: '89010010011',
    name: 'Taste of the Wild High Prairie Canine 12.2kg',
    category: 'Dog Food',
    brand: 'Taste of the Wild',
    unit: 'packet',
    purchasePrice: 6800,
    sellingPrice: 8700,
    mrp: 9200,
    taxPercent: 18,
    minStockLevel: 3,
    reorderLevel: 6,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-012',
    sku: 'DF-ARD-012',
    barcode: '89010010012',
    name: 'Arden Grange Adult Fresh Chicken 12kg',
    category: 'Dog Food',
    brand: 'Arden Grange',
    unit: 'packet',
    purchasePrice: 4900,
    sellingPrice: 6300,
    mrp: 6700,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },

  // CAT FOOD (10 items)
  {
    id: 'prod-013',
    sku: 'CF-RC-013',
    barcode: '89010010013',
    name: 'Royal Canin Kitten Second Age 4kg',
    category: 'Cat Food',
    brand: 'Royal Canin',
    unit: 'packet',
    purchasePrice: 2600,
    sellingPrice: 3350,
    mrp: 3600,
    taxPercent: 18,
    minStockLevel: 6,
    reorderLevel: 12,
    supplierId: 'sup-1',
    supplierName: 'Royal Canin India Pvt Ltd',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-014',
    sku: 'CF-RC-014',
    barcode: '89010010014',
    name: 'Royal Canin Persian Adult Cat 4kg',
    category: 'Cat Food',
    brand: 'Royal Canin',
    unit: 'packet',
    purchasePrice: 2800,
    sellingPrice: 3650,
    mrp: 3900,
    taxPercent: 18,
    minStockLevel: 8,
    reorderLevel: 15,
    supplierId: 'sup-1',
    supplierName: 'Royal Canin India Pvt Ltd',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-015',
    sku: 'CF-WHI-015',
    barcode: '89010010015',
    name: 'Whiskas Ocean Fish Adult Cat Food 7kg',
    category: 'Cat Food',
    brand: 'Whiskas',
    unit: 'packet',
    purchasePrice: 1550,
    sellingPrice: 1999,
    mrp: 2200,
    taxPercent: 18,
    minStockLevel: 10,
    reorderLevel: 20,
    supplierId: 'sup-2',
    supplierName: 'Mars Petcare India',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-016',
    sku: 'CF-WHI-016',
    barcode: '89010010016',
    name: 'Whiskas Tuna in Jelly Wet Cat Food 85g (Pack of 12)',
    category: 'Cat Food',
    brand: 'Whiskas',
    unit: 'box',
    purchasePrice: 420,
    sellingPrice: 540,
    mrp: 600,
    taxPercent: 18,
    minStockLevel: 15,
    reorderLevel: 30,
    supplierId: 'sup-2',
    supplierName: 'Mars Petcare India',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-017',
    sku: 'CF-FAR-017',
    barcode: '89010010017',
    name: 'Farmina N&D Ocean Cod Fish & Orange Cat 5kg',
    category: 'Cat Food',
    brand: 'Farmina',
    unit: 'packet',
    purchasePrice: 3900,
    sellingPrice: 4990,
    mrp: 5350,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-018',
    sku: 'CF-SHE-018',
    barcode: '89010010018',
    name: 'Sheba Premium Succulent Chicken Breast Loaf 70g (12 Cans)',
    category: 'Cat Food',
    brand: 'Sheba',
    unit: 'box',
    purchasePrice: 650,
    sellingPrice: 840,
    mrp: 900,
    taxPercent: 18,
    minStockLevel: 10,
    reorderLevel: 25,
    supplierId: 'sup-2',
    supplierName: 'Mars Petcare India',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-019',
    sku: 'CF-MEO-019',
    barcode: '89010010019',
    name: 'Me-O Persian Anti Hairball Cat Food 7kg',
    category: 'Cat Food',
    brand: 'Me-O',
    unit: 'packet',
    purchasePrice: 1750,
    sellingPrice: 2250,
    mrp: 2450,
    taxPercent: 18,
    minStockLevel: 8,
    reorderLevel: 16,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-020',
    sku: 'CF-HIL-020',
    barcode: '89010010020',
    name: "Hill's Science Diet Indoor Adult Cat 3.1kg",
    category: 'Cat Food',
    brand: "Hill's",
    unit: 'packet',
    purchasePrice: 2300,
    sellingPrice: 2990,
    mrp: 3200,
    taxPercent: 18,
    minStockLevel: 5,
    reorderLevel: 10,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-021',
    sku: 'CF-PUR-021',
    barcode: '89010010021',
    name: 'Purepet Ocean Fish Adult Cat Food 7kg',
    category: 'Cat Food',
    brand: 'Purepet',
    unit: 'packet',
    purchasePrice: 950,
    sellingPrice: 1250,
    mrp: 1400,
    taxPercent: 18,
    minStockLevel: 10,
    reorderLevel: 20,
    supplierId: 'sup-3',
    supplierName: 'Drools Pet Food Pvt Ltd',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-022',
    sku: 'CF-FEL-022',
    barcode: '89010010022',
    name: 'Felix As Good As It Looks Kitten Jelly 85g x 12',
    category: 'Cat Food',
    brand: 'Felix',
    unit: 'box',
    purchasePrice: 480,
    sellingPrice: 620,
    mrp: 660,
    taxPercent: 18,
    minStockLevel: 12,
    reorderLevel: 24,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'cat',
    status: 'ACTIVE',
  },

  // BIRD FOOD (8 items)
  {
    id: 'prod-023',
    sku: 'BF-VER-023',
    barcode: '89010010023',
    name: 'Versele-Laga Prestige Budgies Seed Mix 1kg',
    category: 'Bird Food',
    brand: 'Versele-Laga',
    unit: 'packet',
    purchasePrice: 380,
    sellingPrice: 520,
    mrp: 580,
    taxPercent: 12,
    minStockLevel: 8,
    reorderLevel: 15,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'bird',
    status: 'ACTIVE',
  },
  {
    id: 'prod-024',
    sku: 'BF-ZUP-024',
    barcode: '89010010024',
    name: 'ZuPreem FruitBlend Pellets Cockatiel 900g',
    category: 'Bird Food',
    brand: 'ZuPreem',
    unit: 'packet',
    purchasePrice: 850,
    sellingPrice: 1190,
    mrp: 1300,
    taxPercent: 12,
    minStockLevel: 6,
    reorderLevel: 12,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'bird',
    status: 'ACTIVE',
  },
  {
    id: 'prod-025',
    sku: 'BF-VIT-025',
    barcode: '89010010025',
    name: 'Vitapol Economic Food for Cockatiel 1.2kg',
    category: 'Bird Food',
    brand: 'Vitapol',
    unit: 'packet',
    purchasePrice: 320,
    sellingPrice: 450,
    mrp: 500,
    taxPercent: 12,
    minStockLevel: 8,
    reorderLevel: 16,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'bird',
    status: 'ACTIVE',
  },
  {
    id: 'prod-026',
    sku: 'BF-BOL-026',
    barcode: '89010010026',
    name: 'Boltz Bird Food for Budgies Clean Seeds 1.2kg',
    category: 'Bird Food',
    brand: 'Boltz',
    unit: 'packet',
    purchasePrice: 210,
    sellingPrice: 299,
    mrp: 350,
    taxPercent: 12,
    minStockLevel: 10,
    reorderLevel: 20,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'bird',
    status: 'ACTIVE',
  },
  {
    id: 'prod-027',
    sku: 'BF-HAR-027',
    barcode: '89010010027',
    name: "Harrison's Adult Lifetime Fine Organic Bird 454g",
    category: 'Bird Food',
    brand: "Harrison's",
    unit: 'packet',
    purchasePrice: 1200,
    sellingPrice: 1650,
    mrp: 1800,
    taxPercent: 12,
    minStockLevel: 3,
    reorderLevel: 6,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'bird',
    status: 'ACTIVE',
  },
  {
    id: 'prod-028',
    sku: 'BF-KAY-028',
    barcode: '89010010028',
    name: 'Kaytee Forti-Diet Pro Health Canary Food 1.36kg',
    category: 'Bird Food',
    brand: 'Kaytee',
    unit: 'packet',
    purchasePrice: 620,
    sellingPrice: 850,
    mrp: 950,
    taxPercent: 12,
    minStockLevel: 5,
    reorderLevel: 10,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'bird',
    status: 'ACTIVE',
  },
  {
    id: 'prod-029',
    sku: 'BF-RIO-029',
    barcode: '89010010029',
    name: 'Rio Daily Feed for Exotic Finches 1kg',
    category: 'Bird Food',
    brand: 'Rio',
    unit: 'packet',
    purchasePrice: 340,
    sellingPrice: 480,
    mrp: 520,
    taxPercent: 12,
    minStockLevel: 6,
    reorderLevel: 12,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'bird',
    status: 'ACTIVE',
  },
  {
    id: 'prod-030',
    sku: 'BF-VIT-030',
    barcode: '89010010030',
    name: 'Vitapol Smakers Treat Sticks for Lovebirds (Pack of 2)',
    category: 'Bird Food',
    brand: 'Vitapol',
    unit: 'packet',
    purchasePrice: 140,
    sellingPrice: 220,
    mrp: 260,
    taxPercent: 12,
    minStockLevel: 12,
    reorderLevel: 25,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'bird',
    status: 'ACTIVE',
  },

  // FISH FOOD (8 items)
  {
    id: 'prod-031',
    sku: 'FF-HIK-031',
    barcode: '89010010031',
    name: 'Hikari Micro Wafers Tropical Fish Food 45g',
    category: 'Fish Food',
    brand: 'Hikari',
    unit: 'packet',
    purchasePrice: 360,
    sellingPrice: 490,
    mrp: 550,
    taxPercent: 12,
    minStockLevel: 10,
    reorderLevel: 20,
    supplierId: 'sup-5',
    supplierName: 'Aquaria World & Exotic Marine',
    avatarType: 'fish',
    status: 'ACTIVE',
  },
  {
    id: 'prod-032',
    sku: 'FF-TET-032',
    barcode: '89010010032',
    name: 'Tetra Bits Complete Discus & Tropical 300g (1000ml)',
    category: 'Fish Food',
    brand: 'Tetra',
    unit: 'can',
    purchasePrice: 650,
    sellingPrice: 899,
    mrp: 990,
    taxPercent: 12,
    minStockLevel: 8,
    reorderLevel: 16,
    supplierId: 'sup-5',
    supplierName: 'Aquaria World & Exotic Marine',
    avatarType: 'fish',
    status: 'ACTIVE',
  },
  {
    id: 'prod-033',
    sku: 'FF-TAI-033',
    barcode: '89010010033',
    name: 'Taiyo Grow Fish Food Pellets 500g',
    category: 'Fish Food',
    brand: 'Taiyo',
    unit: 'packet',
    purchasePrice: 110,
    sellingPrice: 165,
    mrp: 190,
    taxPercent: 12,
    minStockLevel: 15,
    reorderLevel: 30,
    supplierId: 'sup-5',
    supplierName: 'Aquaria World & Exotic Marine',
    avatarType: 'fish',
    status: 'ACTIVE',
  },
  {
    id: 'prod-034',
    sku: 'FF-OPT-034',
    barcode: '89010010034',
    name: 'Optimum Betta Mini Pellets with Spirulina 20g',
    category: 'Fish Food',
    brand: 'Optimum',
    unit: 'packet',
    purchasePrice: 75,
    sellingPrice: 120,
    mrp: 140,
    taxPercent: 12,
    minStockLevel: 20,
    reorderLevel: 40,
    supplierId: 'sup-5',
    supplierName: 'Aquaria World & Exotic Marine',
    avatarType: 'fish',
    status: 'ACTIVE',
  },
  {
    id: 'prod-035',
    sku: 'FF-SER-035',
    barcode: '89010010035',
    name: 'Sera Vipan Staple Flake Food 1000ml',
    category: 'Fish Food',
    brand: 'Sera',
    unit: 'can',
    purchasePrice: 780,
    sellingPrice: 1050,
    mrp: 1180,
    taxPercent: 12,
    minStockLevel: 6,
    reorderLevel: 12,
    supplierId: 'sup-5',
    supplierName: 'Aquaria World & Exotic Marine',
    avatarType: 'fish',
    status: 'ACTIVE',
  },
  {
    id: 'prod-036',
    sku: 'FF-OCE-036',
    barcode: '89010010036',
    name: 'Ocean Free AR-G2 Pro Arowana Carnivorous Pellet 500g',
    category: 'Fish Food',
    brand: 'Ocean Free',
    unit: 'can',
    purchasePrice: 1400,
    sellingPrice: 1890,
    mrp: 2100,
    taxPercent: 12,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-5',
    supplierName: 'Aquaria World & Exotic Marine',
    avatarType: 'fish',
    status: 'ACTIVE',
  },
  {
    id: 'prod-037',
    sku: 'FF-HIK-037',
    barcode: '89010010037',
    name: 'Hikari Algae Wafers Plecostomus & Bottom Feeders 82g',
    category: 'Fish Food',
    brand: 'Hikari',
    unit: 'packet',
    purchasePrice: 420,
    sellingPrice: 580,
    mrp: 650,
    taxPercent: 12,
    minStockLevel: 8,
    reorderLevel: 16,
    supplierId: 'sup-5',
    supplierName: 'Aquaria World & Exotic Marine',
    avatarType: 'fish',
    status: 'ACTIVE',
  },
  {
    id: 'prod-038',
    sku: 'FF-DYM-038',
    barcode: '89010010038',
    name: 'Dymax Spirulina Discus Floating Bites 120g',
    category: 'Fish Food',
    brand: 'Dymax',
    unit: 'can',
    purchasePrice: 320,
    sellingPrice: 450,
    mrp: 500,
    taxPercent: 12,
    minStockLevel: 10,
    reorderLevel: 20,
    supplierId: 'sup-5',
    supplierName: 'Aquaria World & Exotic Marine',
    avatarType: 'fish',
    status: 'ACTIVE',
  },

  // PET TREATS (8 items)
  {
    id: 'prod-039',
    sku: 'TR-JER-039',
    barcode: '89010010039',
    name: 'JerHigh Milky Dog Sticks Real Chicken 70g',
    category: 'Pet Treats',
    brand: 'JerHigh',
    unit: 'packet',
    purchasePrice: 115,
    sellingPrice: 165,
    mrp: 185,
    taxPercent: 18,
    minStockLevel: 20,
    reorderLevel: 40,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-040',
    sku: 'TR-GNA-040',
    barcode: '89010010040',
    name: 'Gnawlers Calcium Milk Dental Bone Small (30 pcs)',
    category: 'Pet Treats',
    brand: 'Gnawlers',
    unit: 'box',
    purchasePrice: 350,
    sellingPrice: 499,
    mrp: 550,
    taxPercent: 18,
    minStockLevel: 10,
    reorderLevel: 20,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-041',
    sku: 'TR-TEM-041',
    barcode: '89010010041',
    name: 'Temptations Tasty Chicken Crunchy Cat Treats 85g',
    category: 'Pet Treats',
    brand: 'Temptations',
    unit: 'packet',
    purchasePrice: 130,
    sellingPrice: 180,
    mrp: 200,
    taxPercent: 18,
    minStockLevel: 15,
    reorderLevel: 30,
    supplierId: 'sup-2',
    supplierName: 'Mars Petcare India',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-042',
    sku: 'TR-DRO-042',
    barcode: '89010010042',
    name: 'Drools Absolute Calcium Sausage Treats 400g',
    category: 'Pet Treats',
    brand: 'Drools',
    unit: 'box',
    purchasePrice: 220,
    sellingPrice: 310,
    mrp: 350,
    taxPercent: 18,
    minStockLevel: 12,
    reorderLevel: 25,
    supplierId: 'sup-3',
    supplierName: 'Drools Pet Food Pvt Ltd',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-043',
    sku: 'TR-DOG-043',
    barcode: '89010010043',
    name: 'Dogaholic Milky Chew Rawhide Braided Sticks 5-inch',
    category: 'Pet Treats',
    brand: 'Dogaholic',
    unit: 'packet',
    purchasePrice: 180,
    sellingPrice: 260,
    mrp: 290,
    taxPercent: 18,
    minStockLevel: 15,
    reorderLevel: 30,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-044',
    sku: 'TR-PED-044',
    barcode: '89010010044',
    name: 'Pedigree Dentastix Medium Dog Oral Care 7 Sticks',
    category: 'Pet Treats',
    brand: 'Pedigree',
    unit: 'packet',
    purchasePrice: 195,
    sellingPrice: 260,
    mrp: 285,
    taxPercent: 18,
    minStockLevel: 15,
    reorderLevel: 35,
    supplierId: 'sup-2',
    supplierName: 'Mars Petcare India',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-045',
    sku: 'TR-CHI-045',
    barcode: '89010010045',
    name: 'Chip Chops Roast Duck Strips Soft Treats 70g',
    category: 'Pet Treats',
    brand: 'Chip Chops',
    unit: 'packet',
    purchasePrice: 140,
    sellingPrice: 210,
    mrp: 240,
    taxPercent: 18,
    minStockLevel: 12,
    reorderLevel: 25,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-046',
    sku: 'TR-SHE-046',
    barcode: '89010010046',
    name: 'Sheba Melty Creamy Cat Treat Chicken Sachets (4x12g)',
    category: 'Pet Treats',
    brand: 'Sheba',
    unit: 'packet',
    purchasePrice: 110,
    sellingPrice: 150,
    mrp: 170,
    taxPercent: 18,
    minStockLevel: 20,
    reorderLevel: 40,
    supplierId: 'sup-2',
    supplierName: 'Mars Petcare India',
    avatarType: 'cat',
    status: 'ACTIVE',
  },

  // TOYS (8 items)
  {
    id: 'prod-047',
    sku: 'TY-KON-047',
    barcode: '89010010047',
    name: 'KONG Classic Durable Natural Rubber Dog Toy (Large)',
    category: 'Toys',
    brand: 'KONG',
    unit: 'piece',
    purchasePrice: 780,
    sellingPrice: 1150,
    mrp: 1299,
    taxPercent: 18,
    minStockLevel: 5,
    reorderLevel: 10,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-048',
    sku: 'TY-GIG-048',
    barcode: '89010010048',
    name: 'GiGwi Plush Squeaker Duck with Removable Sound Unit',
    category: 'Toys',
    brand: 'GiGwi',
    unit: 'piece',
    purchasePrice: 420,
    sellingPrice: 650,
    mrp: 750,
    taxPercent: 18,
    minStockLevel: 6,
    reorderLevel: 12,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-049',
    sku: 'TY-CAT-049',
    barcode: '89010010049',
    name: 'PetVogue Automatic Interactive LED Laser Cat Toy',
    category: 'Toys',
    brand: 'PetVogue',
    unit: 'piece',
    purchasePrice: 490,
    sellingPrice: 799,
    mrp: 899,
    taxPercent: 18,
    minStockLevel: 6,
    reorderLevel: 12,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-050',
    sku: 'TY-TRI-050',
    barcode: '89010010050',
    name: 'Trixie Denta Fun Cotton Knot Rope Ball 26cm',
    category: 'Toys',
    brand: 'Trixie',
    unit: 'piece',
    purchasePrice: 180,
    sellingPrice: 280,
    mrp: 320,
    taxPercent: 18,
    minStockLevel: 10,
    reorderLevel: 20,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-051',
    sku: 'TY-NIN-051',
    barcode: '89010010051',
    name: 'Nina Ottosson Dog Smart Interactive Brain Puzzle Game',
    category: 'Toys',
    brand: 'Outward Hound',
    unit: 'piece',
    purchasePrice: 1100,
    sellingPrice: 1599,
    mrp: 1799,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-052',
    sku: 'TY-CAT-052',
    barcode: '89010010052',
    name: 'Catch Me Feather Teaser Wand with Bell for Cats',
    category: 'Toys',
    brand: 'CatPro',
    unit: 'piece',
    purchasePrice: 90,
    sellingPrice: 180,
    mrp: 220,
    taxPercent: 18,
    minStockLevel: 15,
    reorderLevel: 30,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-053',
    sku: 'TY-JWP-053',
    barcode: '89010010053',
    name: 'JW Pet Hol-ee Roller Natural Rubber Treat Ball Medium',
    category: 'Toys',
    brand: 'JW Pet',
    unit: 'piece',
    purchasePrice: 380,
    sellingPrice: 560,
    mrp: 650,
    taxPercent: 18,
    minStockLevel: 6,
    reorderLevel: 12,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-054',
    sku: 'TY-BIR-054',
    barcode: '89010010054',
    name: 'Birdie Paradise Wooden Mirror & Bell Perch Toy',
    category: 'Toys',
    brand: 'BirdPro',
    unit: 'piece',
    purchasePrice: 120,
    sellingPrice: 220,
    mrp: 260,
    taxPercent: 18,
    minStockLevel: 10,
    reorderLevel: 20,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'bird',
    status: 'ACTIVE',
  },

  // LEASHES & COLLARS (8 items)
  {
    id: 'prod-055',
    sku: 'LC-ROG-055',
    barcode: '89010010055',
    name: 'Rogz Alpinist Utility Reflective Dog Harness (Large)',
    category: 'Leashes & Collars',
    brand: 'Rogz',
    unit: 'piece',
    purchasePrice: 950,
    sellingPrice: 1450,
    mrp: 1650,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-056',
    sku: 'LC-FLX-056',
    barcode: '89010010056',
    name: 'Flexi New Classic Retractable Tape Leash 5M (Up to 25kg)',
    category: 'Leashes & Collars',
    brand: 'Flexi',
    unit: 'piece',
    purchasePrice: 1250,
    sellingPrice: 1799,
    mrp: 1999,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-057',
    sku: 'LC-PAW-057',
    barcode: '89010010057',
    name: 'Pawzone Neoprene Padded Anti-Choke Collar Red (Medium)',
    category: 'Leashes & Collars',
    brand: 'Pawzone',
    unit: 'piece',
    purchasePrice: 280,
    sellingPrice: 450,
    mrp: 520,
    taxPercent: 18,
    minStockLevel: 8,
    reorderLevel: 16,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-058',
    sku: 'LC-CAT-058',
    barcode: '89010010058',
    name: 'Breakaway Safety Bell Cat Collar with Reflective Stripe',
    category: 'Leashes & Collars',
    brand: 'PetSafe',
    unit: 'piece',
    purchasePrice: 95,
    sellingPrice: 180,
    mrp: 220,
    taxPercent: 18,
    minStockLevel: 15,
    reorderLevel: 30,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-059',
    sku: 'LC-TRI-059',
    barcode: '89010010059',
    name: 'Trixie Premium Padded Dog Harness Black XL',
    category: 'Leashes & Collars',
    brand: 'Trixie',
    unit: 'piece',
    purchasePrice: 850,
    sellingPrice: 1290,
    mrp: 1450,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-060',
    sku: 'LC-RED-060',
    barcode: '89010010060',
    name: 'Red Dingo Stainless Steel Personalized Dog ID Tag Bone',
    category: 'Leashes & Collars',
    brand: 'Red Dingo',
    unit: 'piece',
    purchasePrice: 250,
    sellingPrice: 420,
    mrp: 490,
    taxPercent: 18,
    minStockLevel: 10,
    reorderLevel: 20,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-061',
    sku: 'LC-MIL-061',
    barcode: '89010010061',
    name: 'Tactical Military Bungee Training Leash with Traffic Handle',
    category: 'Leashes & Collars',
    brand: 'K9 Elite',
    unit: 'piece',
    purchasePrice: 620,
    sellingPrice: 980,
    mrp: 1150,
    taxPercent: 18,
    minStockLevel: 5,
    reorderLevel: 10,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-062',
    sku: 'LC-LED-062',
    barcode: '89010010062',
    name: 'USB Rechargeable Glow LED Night Dog Safety Collar Green',
    category: 'Leashes & Collars',
    brand: 'NiteHowl',
    unit: 'piece',
    purchasePrice: 320,
    sellingPrice: 550,
    mrp: 650,
    taxPercent: 18,
    minStockLevel: 8,
    reorderLevel: 15,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },

  // BEDS & MATS (7 items)
  {
    id: 'prod-063',
    sku: 'BM-BED-063',
    barcode: '89010010063',
    name: 'Bedsure Orthopedic Memory Foam Dog Sofa Bed Large (Grey)',
    category: 'Beds & Mats',
    brand: 'Bedsure',
    unit: 'piece',
    purchasePrice: 2400,
    sellingPrice: 3590,
    mrp: 3990,
    taxPercent: 18,
    minStockLevel: 3,
    reorderLevel: 6,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-064',
    sku: 'BM-CUR-064',
    barcode: '89010010064',
    name: 'Curver Knit Cozy Round Pet Bed & Cave Mint Green',
    category: 'Beds & Mats',
    brand: 'Curver',
    unit: 'piece',
    purchasePrice: 2800,
    sellingPrice: 4200,
    mrp: 4600,
    taxPercent: 18,
    minStockLevel: 2,
    reorderLevel: 5,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-065',
    sku: 'BM-TRI-065',
    barcode: '89010010065',
    name: 'Trixie Fluffy Anti-Anxiety Plush Donut Bed (Medium 65cm)',
    category: 'Beds & Mats',
    brand: 'Trixie',
    unit: 'piece',
    purchasePrice: 1400,
    sellingPrice: 2190,
    mrp: 2490,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-066',
    sku: 'BM-FUR-066',
    barcode: '89010010066',
    name: 'Furhaven Self-Cooling Gel Mat for Dogs & Cats 90x50cm',
    category: 'Beds & Mats',
    brand: 'Furhaven',
    unit: 'piece',
    purchasePrice: 850,
    sellingPrice: 1350,
    mrp: 1550,
    taxPercent: 18,
    minStockLevel: 6,
    reorderLevel: 12,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-067',
    sku: 'BM-HAM-067',
    barcode: '89010010067',
    name: 'Sunny Seat Cat Window Mounted Hammock Perch (Holds 15kg)',
    category: 'Beds & Mats',
    brand: 'SunnySeat',
    unit: 'piece',
    purchasePrice: 650,
    sellingPrice: 1090,
    mrp: 1250,
    taxPercent: 18,
    minStockLevel: 5,
    reorderLevel: 10,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-068',
    sku: 'BM-CRA-068',
    barcode: '89010010068',
    name: 'MidWest QuietTime Deluxe Fleece Pet Crate Mat 36-inch',
    category: 'Beds & Mats',
    brand: 'MidWest',
    unit: 'piece',
    purchasePrice: 750,
    sellingPrice: 1190,
    mrp: 1350,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-069',
    sku: 'BM-CAR-069',
    barcode: '89010010069',
    name: 'Waterproof Dog Car Seat Cover with Mesh Window Hammock',
    category: 'Beds & Mats',
    brand: 'Vailge',
    unit: 'piece',
    purchasePrice: 1100,
    sellingPrice: 1690,
    mrp: 1890,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },

  // GROOMING (8 items)
  {
    id: 'prod-070',
    sku: 'GR-WAH-070',
    barcode: '89010010070',
    name: 'Wahl Oatmeal & Coconut Pet Conditioning Shampoo 750ml',
    category: 'Grooming',
    brand: 'Wahl',
    unit: 'bottle',
    purchasePrice: 480,
    sellingPrice: 699,
    mrp: 790,
    taxPercent: 18,
    minStockLevel: 8,
    reorderLevel: 16,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-071',
    sku: 'GR-HIM-071',
    barcode: '89010010071',
    name: 'Himalaya Erina Plus Anti-Dandruff Coat Cleanser 200ml',
    category: 'Grooming',
    brand: 'Himalaya',
    unit: 'bottle',
    purchasePrice: 150,
    sellingPrice: 220,
    mrp: 250,
    taxPercent: 18,
    minStockLevel: 15,
    reorderLevel: 30,
    supplierId: 'sup-6',
    supplierName: 'VetCare India Pharmaceuticals',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-072',
    sku: 'GR-FUR-072',
    barcode: '89010010072',
    name: 'FURminator Undercoat deShedding Tool Medium Long Hair',
    category: 'Grooming',
    brand: 'FURminator',
    unit: 'piece',
    purchasePrice: 1450,
    sellingPrice: 2199,
    mrp: 2450,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-073',
    sku: 'GR-TRO-073',
    barcode: '89010010073',
    name: 'TropiClean Papaya & Coconut 2-in-1 Pet Shampoo & Conditioner 355ml',
    category: 'Grooming',
    brand: 'TropiClean',
    unit: 'bottle',
    purchasePrice: 590,
    sellingPrice: 850,
    mrp: 950,
    taxPercent: 18,
    minStockLevel: 6,
    reorderLevel: 12,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-074',
    sku: 'GR-BIO-074',
    barcode: '89010010074',
    name: 'Bioline Herbal Ear Care Drops for Dogs & Cats 50ml',
    category: 'Grooming',
    brand: 'Bioline',
    unit: 'bottle',
    purchasePrice: 180,
    sellingPrice: 275,
    mrp: 310,
    taxPercent: 18,
    minStockLevel: 10,
    reorderLevel: 20,
    supplierId: 'sup-6',
    supplierName: 'VetCare India Pharmaceuticals',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-075',
    sku: 'GR-PET-075',
    barcode: '89010010075',
    name: 'Petkin Bamboo Eco Pet Wipes with Aloe (Pack of 80)',
    category: 'Grooming',
    brand: 'Petkin',
    unit: 'packet',
    purchasePrice: 220,
    sellingPrice: 350,
    mrp: 395,
    taxPercent: 18,
    minStockLevel: 12,
    reorderLevel: 25,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-076',
    sku: 'GR-NAI-076',
    barcode: '89010010076',
    name: 'Professional Stainless Steel Pet Nail Clipper with Quick Sensor Guard',
    category: 'Grooming',
    brand: 'PawGroom',
    unit: 'piece',
    purchasePrice: 180,
    sellingPrice: 299,
    mrp: 350,
    taxPercent: 18,
    minStockLevel: 8,
    reorderLevel: 16,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-077',
    sku: 'GR-SLI-077',
    barcode: '89010010077',
    name: 'Self-Cleaning Slicker Brush for Shedding Pets',
    category: 'Grooming',
    brand: 'PetClean',
    unit: 'piece',
    purchasePrice: 240,
    sellingPrice: 399,
    mrp: 450,
    taxPercent: 18,
    minStockLevel: 10,
    reorderLevel: 20,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },

  // MEDICINES & CARE (9 items)
  {
    id: 'prod-078',
    sku: 'MD-BRA-078',
    barcode: '89010010078',
    name: 'Bravecto Chewable Tablet for Dogs 20-40kg (3 Months Protection)',
    category: 'Medicines & Care',
    brand: 'MSD Animal Health',
    unit: 'piece',
    purchasePrice: 1850,
    sellingPrice: 2490,
    mrp: 2700,
    taxPercent: 12,
    minStockLevel: 5,
    reorderLevel: 10,
    supplierId: 'sup-6',
    supplierName: 'VetCare India Pharmaceuticals',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-079',
    sku: 'MD-NEX-079',
    barcode: '89010010079',
    name: 'NexGard Spectra Flea Tick & Dewormer Chewable 15-30kg',
    category: 'Medicines & Care',
    brand: 'Boehringer Ingelheim',
    unit: 'piece',
    purchasePrice: 1100,
    sellingPrice: 1499,
    mrp: 1650,
    taxPercent: 12,
    minStockLevel: 6,
    reorderLevel: 12,
    supplierId: 'sup-6',
    supplierName: 'VetCare India Pharmaceuticals',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-080',
    sku: 'MD-FIP-080',
    barcode: '89010010080',
    name: 'Fiprofort Plus Spot On Pipette for Cats 0.5ml',
    category: 'Medicines & Care',
    brand: 'Sava Vet',
    unit: 'piece',
    purchasePrice: 190,
    sellingPrice: 290,
    mrp: 320,
    taxPercent: 12,
    minStockLevel: 12,
    reorderLevel: 24,
    supplierId: 'sup-6',
    supplierName: 'VetCare India Pharmaceuticals',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-081',
    sku: 'MD-VIR-081',
    barcode: '89010010081',
    name: 'Virbac Nutri-Plus Gel High Energy Nutritional Supplement 120.5g',
    category: 'Medicines & Care',
    brand: 'Virbac',
    unit: 'piece',
    purchasePrice: 420,
    sellingPrice: 590,
    mrp: 650,
    taxPercent: 12,
    minStockLevel: 8,
    reorderLevel: 16,
    supplierId: 'sup-6',
    supplierName: 'VetCare India Pharmaceuticals',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-082',
    sku: 'MD-HIM-082',
    barcode: '89010010082',
    name: 'Himalaya Digyton Digestive Drops for Dogs & Cats 30ml',
    category: 'Medicines & Care',
    brand: 'Himalaya',
    unit: 'bottle',
    purchasePrice: 95,
    sellingPrice: 145,
    mrp: 165,
    taxPercent: 12,
    minStockLevel: 15,
    reorderLevel: 30,
    supplierId: 'sup-6',
    supplierName: 'VetCare India Pharmaceuticals',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-083',
    sku: 'MD-PET-083',
    barcode: '89010010083',
    name: 'Petstar Multivitamin & Amino Acids Syrup 200ml',
    category: 'Medicines & Care',
    brand: 'Mankind Vet',
    unit: 'bottle',
    purchasePrice: 180,
    sellingPrice: 270,
    mrp: 300,
    taxPercent: 12,
    minStockLevel: 10,
    reorderLevel: 20,
    supplierId: 'sup-6',
    supplierName: 'VetCare India Pharmaceuticals',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-084',
    sku: 'MD-CAN-084',
    barcode: '89010010084',
    name: 'Canina Calcium Carbonate Bone Strength Powder 400g',
    category: 'Medicines & Care',
    brand: 'Canina',
    unit: 'box',
    purchasePrice: 520,
    sellingPrice: 750,
    mrp: 850,
    taxPercent: 12,
    minStockLevel: 6,
    reorderLevel: 12,
    supplierId: 'sup-6',
    supplierName: 'VetCare India Pharmaceuticals',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-085',
    sku: 'MD-SYR-085',
    barcode: '89010010085',
    name: 'Vivaldis Renalof Pet Kidney Stone Care Syrup 100ml',
    category: 'Medicines & Care',
    brand: 'Vivaldis',
    unit: 'bottle',
    purchasePrice: 780,
    sellingPrice: 1090,
    mrp: 1200,
    taxPercent: 12,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-6',
    supplierName: 'VetCare India Pharmaceuticals',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-086',
    sku: 'MD-EYE-086',
    barcode: '89010010086',
    name: 'Cipla Ciplox Eye/Ear Drops 10ml for Pets',
    category: 'Medicines & Care',
    brand: 'Cipla Vet',
    unit: 'bottle',
    purchasePrice: 35,
    sellingPrice: 65,
    mrp: 75,
    taxPercent: 12,
    minStockLevel: 20,
    reorderLevel: 40,
    supplierId: 'sup-6',
    supplierName: 'VetCare India Pharmaceuticals',
    avatarType: 'dog',
    status: 'ACTIVE',
  },

  // ACCESSORIES (8 items)
  {
    id: 'prod-087',
    sku: 'AC-BOW-087',
    barcode: '89010010087',
    name: 'Anti-Skid Heavy Stainless Steel Pet Bowl 900ml',
    category: 'Accessories',
    brand: 'PetPro',
    unit: 'piece',
    purchasePrice: 190,
    sellingPrice: 320,
    mrp: 380,
    taxPercent: 18,
    minStockLevel: 12,
    reorderLevel: 24,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-088',
    sku: 'AC-LIT-088',
    barcode: '89010010088',
    name: 'Hooded Enclosed Cat Litter Box with Carbon Filter & Scoop',
    category: 'Accessories',
    brand: 'Moderna',
    unit: 'piece',
    purchasePrice: 1250,
    sellingPrice: 1890,
    mrp: 2190,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-089',
    sku: 'AC-SAN-089',
    barcode: '89010010089',
    name: 'Bentonite Clumping Cat Litter Lavender Scent 10kg',
    category: 'Accessories',
    brand: 'Intersand',
    unit: 'packet',
    purchasePrice: 420,
    sellingPrice: 650,
    mrp: 750,
    taxPercent: 18,
    minStockLevel: 15,
    reorderLevel: 30,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-090',
    sku: 'AC-SLO-090',
    barcode: '89010010090',
    name: 'Trixie Slow Feed Anti-Gulping Interactive Dog Bowl',
    category: 'Accessories',
    brand: 'Trixie',
    unit: 'piece',
    purchasePrice: 310,
    sellingPrice: 490,
    mrp: 550,
    taxPercent: 18,
    minStockLevel: 8,
    reorderLevel: 16,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-091',
    sku: 'AC-CAR-091',
    barcode: '89010010091',
    name: 'Skudo IATA Approved Pet Travel Carrier Box Size 3 (Up to 12kg)',
    category: 'Accessories',
    brand: 'Skudo',
    unit: 'piece',
    purchasePrice: 2200,
    sellingPrice: 3400,
    mrp: 3800,
    taxPercent: 18,
    minStockLevel: 3,
    reorderLevel: 6,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-092',
    sku: 'AC-FOU-092',
    barcode: '89010010092',
    name: 'Catit Flower Pet Drinking Fountain with Triple Action Filter 3L',
    category: 'Accessories',
    brand: 'Catit',
    unit: 'piece',
    purchasePrice: 1600,
    sellingPrice: 2399,
    mrp: 2699,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'cat',
    status: 'ACTIVE',
  },
  {
    id: 'prod-093',
    sku: 'AC-WAU-093',
    barcode: '89010010093',
    name: 'Poop Bag Dispenser with 8 Rolls Biodegradable Bags (120 Bags)',
    category: 'Accessories',
    brand: 'EarthRated',
    unit: 'box',
    purchasePrice: 250,
    sellingPrice: 399,
    mrp: 450,
    taxPercent: 18,
    minStockLevel: 15,
    reorderLevel: 30,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'dog',
    status: 'ACTIVE',
  },
  {
    id: 'prod-094',
    sku: 'AC-SCR-094',
    barcode: '89010010094',
    name: 'Multi-Level Cat Scratching Post Tree with Sisal Rope 85cm',
    category: 'Accessories',
    brand: 'CatTree',
    unit: 'piece',
    purchasePrice: 1800,
    sellingPrice: 2890,
    mrp: 3200,
    taxPercent: 18,
    minStockLevel: 3,
    reorderLevel: 6,
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    avatarType: 'cat',
    status: 'ACTIVE',
  },

  // AQUARIUM PRODUCTS (8 items)
  {
    id: 'prod-095',
    sku: 'AQ-API-095',
    barcode: '89010010095',
    name: 'API Stress Coat Water Conditioner & Aloe Healer 237ml',
    category: 'Aquarium Products',
    brand: 'API',
    unit: 'bottle',
    purchasePrice: 420,
    sellingPrice: 599,
    mrp: 670,
    taxPercent: 18,
    minStockLevel: 6,
    reorderLevel: 12,
    supplierId: 'sup-5',
    supplierName: 'Aquaria World & Exotic Marine',
    avatarType: 'fish',
    status: 'ACTIVE',
  },
  {
    id: 'prod-096',
    sku: 'AQ-SEA-096',
    barcode: '89010010096',
    name: 'Seachem Prime Complete Concentrated Water Dechlorinator 250ml',
    category: 'Aquarium Products',
    brand: 'Seachem',
    unit: 'bottle',
    purchasePrice: 650,
    sellingPrice: 899,
    mrp: 990,
    taxPercent: 18,
    minStockLevel: 6,
    reorderLevel: 12,
    supplierId: 'sup-5',
    supplierName: 'Aquaria World & Exotic Marine',
    avatarType: 'fish',
    status: 'ACTIVE',
  },
  {
    id: 'prod-097',
    sku: 'AQ-SOB-097',
    barcode: '89010010097',
    name: 'SOBO Submersible Internal Filter WP-3000 (1200 L/H)',
    category: 'Aquarium Products',
    brand: 'SOBO',
    unit: 'piece',
    purchasePrice: 450,
    sellingPrice: 699,
    mrp: 799,
    taxPercent: 18,
    minStockLevel: 6,
    reorderLevel: 12,
    supplierId: 'sup-5',
    supplierName: 'Aquaria World & Exotic Marine',
    avatarType: 'fish',
    status: 'ACTIVE',
  },
  {
    id: 'prod-098',
    sku: 'AQ-SUN-098',
    barcode: '89010010098',
    name: 'SunSun External Canister Filter HW-603B Multi-Stage',
    category: 'Aquarium Products',
    brand: 'SunSun',
    unit: 'piece',
    purchasePrice: 1150,
    sellingPrice: 1750,
    mrp: 1950,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-5',
    supplierName: 'Aquaria World & Exotic Marine',
    avatarType: 'fish',
    status: 'ACTIVE',
  },
  {
    id: 'prod-099',
    sku: 'AQ-HEA-099',
    barcode: '89010010099',
    name: 'Eheim Jager Precision Aquarium Thermostatic Heater 100W',
    category: 'Aquarium Products',
    brand: 'Eheim',
    unit: 'piece',
    purchasePrice: 1400,
    sellingPrice: 2090,
    mrp: 2350,
    taxPercent: 18,
    minStockLevel: 4,
    reorderLevel: 8,
    supplierId: 'sup-5',
    supplierName: 'Aquaria World & Exotic Marine',
    avatarType: 'fish',
    status: 'ACTIVE',
  },
  {
    id: 'prod-100',
    sku: 'AQ-LED-100',
    barcode: '89010010100',
    name: 'Chihiros RGB A-Series Aquatic Plant LED Light 45cm',
    category: 'Aquarium Products',
    brand: 'Chihiros',
    unit: 'piece',
    purchasePrice: 2600,
    sellingPrice: 3890,
    mrp: 4300,
    taxPercent: 18,
    minStockLevel: 3,
    reorderLevel: 6,
    supplierId: 'sup-5',
    supplierName: 'Aquaria World & Exotic Marine',
    avatarType: 'fish',
    status: 'ACTIVE',
  },
  {
    id: 'prod-101',
    sku: 'AQ-GRA-101',
    barcode: '89010010101',
    name: 'Natural Black River Aquarium Gravel Substrate 5kg',
    category: 'Aquarium Products',
    brand: 'AquaScape',
    unit: 'packet',
    purchasePrice: 180,
    sellingPrice: 299,
    mrp: 350,
    taxPercent: 18,
    minStockLevel: 10,
    reorderLevel: 20,
    supplierId: 'sup-5',
    supplierName: 'Aquaria World & Exotic Marine',
    avatarType: 'fish',
    status: 'ACTIVE',
  },
  {
    id: 'prod-102',
    sku: 'AQ-BIO-102',
    barcode: '89010010102',
    name: 'Fluval Biomax Biological Filter Rings Media 500g',
    category: 'Aquarium Products',
    brand: 'Fluval',
    unit: 'box',
    purchasePrice: 480,
    sellingPrice: 699,
    mrp: 790,
    taxPercent: 18,
    minStockLevel: 8,
    reorderLevel: 16,
    supplierId: 'sup-5',
    supplierName: 'Aquaria World & Exotic Marine',
    avatarType: 'fish',
    status: 'ACTIVE',
  },
];

// Helper to generate realistic branch stock levels for all products
export function generateInitialInventory(): BranchInventory[] {
  const inventory: BranchInventory[] = [];
  const branchIds = ['branch-1', 'branch-2', 'branch-3', 'branch-4', 'branch-5', 'branch-6'];
  const now = new Date().toISOString();

  // Deterministic realistic stock pattern
  INITIAL_PRODUCTS.forEach((product, idx) => {
    branchIds.forEach((bId, bIndex) => {
      // Calculate realistic stock
      // Some products will be intentionally low stock or near reorder level for demo!
      let qty = 15;
      if (idx === 0) {
        // Royal canin maxi: B1: 25, B2: 18, B3: 40, B4: 12, B5: 31, B6: 20 (as in prompt example)
        const map: Record<string, number> = {
          'branch-1': 25,
          'branch-2': 18,
          'branch-3': 40,
          'branch-4': 12,
          'branch-5': 31,
          'branch-6': 20,
        };
        qty = map[bId] || 20;
      } else if (idx === 2) {
        // Pedigree Adult: B1: 30, B2: 22, B3: 35, B4: 18, B5: 25, B6: 15
        const map: Record<string, number> = {
          'branch-1': 30,
          'branch-2': 22,
          'branch-3': 35,
          'branch-4': 18,
          'branch-5': 25,
          'branch-6': 15,
        };
        qty = map[bId] || 20;
      } else if (idx % 11 === 0) {
        // Low stock simulation in Branch 3 & 4
        qty = bIndex === 2 ? 3 : bIndex === 3 ? 2 : (idx * 3 + bIndex * 7) % 25 + 8;
      } else if (idx % 17 === 0) {
        // Out of stock in Branch 6
        qty = bIndex === 5 ? 0 : (idx * 4 + bIndex * 3) % 20 + 5;
      } else {
        qty = ((idx * 7 + bIndex * 13) % 35) + 6;
      }

      inventory.push({
        branchId: bId,
        productId: product.id,
        quantity: qty,
        lastUpdated: now,
      });
    });
  });

  return inventory;
}

export const INITIAL_STAFF: Staff[] = [
  // Branch 1 (Colaba)
  {
    id: 'staff-01',
    staffCode: 'STF-B01-01',
    name: 'Rajesh Sharma',
    avatarType: 'dog',
    phone: '+91 98201 22331',
    email: 'rajesh.sharma@petworld.co.in',
    address: 'Flat 102, Sunrise Apt, Colaba, Mumbai',
    branchId: 'branch-1',
    branchName: 'Pet World Downtown Flagship',
    designation: 'Branch Manager',
    role: 'BRANCH_MANAGER',
    joiningDate: '2021-03-15',
    basicSalary: 55000,
    status: 'ACTIVE',
    username: 'rajesh_b1',
  },
  {
    id: 'staff-02',
    staffCode: 'STF-B01-02',
    name: 'Deepak Kamble',
    avatarType: 'cat',
    phone: '+91 98202 33442',
    email: 'deepak.k@petworld.co.in',
    address: '45 Sassoon Docks Road, Colaba, Mumbai',
    branchId: 'branch-1',
    branchName: 'Pet World Downtown Flagship',
    designation: 'Cashier',
    role: 'CASHIER',
    joiningDate: '2021-06-01',
    basicSalary: 28000,
    status: 'ACTIVE',
    username: 'deepak_b1',
  },
  {
    id: 'staff-03',
    staffCode: 'STF-B01-03',
    name: 'Sneha Jadhav',
    avatarType: 'rabbit',
    phone: '+91 98203 44553',
    email: 'sneha.j@petworld.co.in',
    address: '12 Cuffe Parade Chawl, Mumbai',
    branchId: 'branch-1',
    branchName: 'Pet World Downtown Flagship',
    designation: 'Sales Staff',
    role: 'SALES_STAFF',
    joiningDate: '2022-02-10',
    basicSalary: 22000,
    status: 'ACTIVE',
    username: 'sneha_b1',
  },
  {
    id: 'staff-04',
    staffCode: 'STF-B01-04',
    name: 'Rohan Naik',
    avatarType: 'fish',
    phone: '+91 98204 55664',
    email: 'rohan.n@petworld.co.in',
    address: 'Near Fort Market, Mumbai',
    branchId: 'branch-1',
    branchName: 'Pet World Downtown Flagship',
    designation: 'Sales Staff',
    role: 'SALES_STAFF',
    joiningDate: '2022-08-15',
    basicSalary: 22000,
    status: 'ACTIVE',
    username: 'rohan_b1',
  },

  // Branch 2 (Bandra)
  {
    id: 'staff-05',
    staffCode: 'STF-B02-01',
    name: 'Priya Mehra',
    avatarType: 'cat',
    phone: '+91 98331 11223',
    email: 'priya.mehra@petworld.co.in',
    address: 'Pali Hill View, Bandra West, Mumbai',
    branchId: 'branch-2',
    branchName: 'Pet World Westside Mall',
    designation: 'Branch Manager',
    role: 'BRANCH_MANAGER',
    joiningDate: '2021-09-10',
    basicSalary: 52000,
    status: 'ACTIVE',
    username: 'priya_b2',
  },
  {
    id: 'staff-06',
    staffCode: 'STF-B02-02',
    name: 'Kavita Menon',
    avatarType: 'dog',
    phone: '+91 98332 22334',
    email: 'kavita.m@petworld.co.in',
    address: 'Hill Road, Bandra West, Mumbai',
    branchId: 'branch-2',
    branchName: 'Pet World Westside Mall',
    designation: 'Cashier',
    role: 'CASHIER',
    joiningDate: '2022-01-15',
    basicSalary: 28000,
    status: 'ACTIVE',
    username: 'kavita_b2',
  },
  {
    id: 'staff-07',
    staffCode: 'STF-B02-03',
    name: 'Gaurav Sawant',
    avatarType: 'bird',
    phone: '+91 98333 33445',
    email: 'gaurav.s@petworld.co.in',
    address: 'Khar Danda, Mumbai',
    branchId: 'branch-2',
    branchName: 'Pet World Westside Mall',
    designation: 'Sales Staff',
    role: 'SALES_STAFF',
    joiningDate: '2023-03-01',
    basicSalary: 21000,
    status: 'ACTIVE',
    username: 'gaurav_b2',
  },

  // Branch 3 (Andheri)
  {
    id: 'staff-08',
    staffCode: 'STF-B03-01',
    name: 'Amit Verma',
    avatarType: 'dog',
    phone: '+91 98111 66778',
    email: 'amit.verma@petworld.co.in',
    address: 'MIDC Cross Rd, Andheri East, Mumbai',
    branchId: 'branch-3',
    branchName: 'Pet World Suburban Plaza',
    designation: 'Branch Manager',
    role: 'BRANCH_MANAGER',
    joiningDate: '2022-04-01',
    basicSalary: 50000,
    status: 'ACTIVE',
    username: 'amit_b3',
  },
  {
    id: 'staff-09',
    staffCode: 'STF-B03-02',
    name: 'Suresh More',
    avatarType: 'hamster',
    phone: '+91 98112 77889',
    email: 'suresh.m@petworld.co.in',
    address: 'Marol Pipeline, Andheri East, Mumbai',
    branchId: 'branch-3',
    branchName: 'Pet World Suburban Plaza',
    designation: 'Cashier',
    role: 'CASHIER',
    joiningDate: '2022-05-15',
    basicSalary: 27000,
    status: 'ACTIVE',
    username: 'suresh_b3',
  },
  {
    id: 'staff-10',
    staffCode: 'STF-B03-03',
    name: 'Pooja Chawla',
    avatarType: 'cat',
    phone: '+91 98113 88990',
    email: 'pooja.c@petworld.co.in',
    address: 'Sahar Village, Andheri, Mumbai',
    branchId: 'branch-3',
    branchName: 'Pet World Suburban Plaza',
    designation: 'Sales Staff',
    role: 'SALES_STAFF',
    joiningDate: '2023-08-20',
    basicSalary: 21000,
    status: 'ACTIVE',
    username: 'pooja_b3',
  },

  // Branch 4 (Powai)
  {
    id: 'staff-11',
    staffCode: 'STF-B04-01',
    name: 'Neha Deshmukh',
    avatarType: 'rabbit',
    phone: '+91 98220 33441',
    email: 'neha.d@petworld.co.in',
    address: 'Hiranandani Heritage, Powai, Mumbai',
    branchId: 'branch-4',
    branchName: 'Pet World Green Valley',
    designation: 'Branch Manager',
    role: 'BRANCH_MANAGER',
    joiningDate: '2022-11-20',
    basicSalary: 52000,
    status: 'ACTIVE',
    username: 'neha_b4',
  },
  {
    id: 'staff-12',
    staffCode: 'STF-B04-02',
    name: 'Vikas Rao',
    avatarType: 'dog',
    phone: '+91 98221 44552',
    email: 'vikas.r@petworld.co.in',
    address: 'Chandivali Farm Rd, Powai, Mumbai',
    branchId: 'branch-4',
    branchName: 'Pet World Green Valley',
    designation: 'Cashier',
    role: 'CASHIER',
    joiningDate: '2023-01-10',
    basicSalary: 27000,
    status: 'ACTIVE',
    username: 'vikas_b4',
  },
  {
    id: 'staff-13',
    staffCode: 'STF-B04-03',
    name: 'Anjali Gupta',
    avatarType: 'bird',
    phone: '+91 98222 55663',
    email: 'anjali.g@petworld.co.in',
    address: 'Kanjurmarg West, Mumbai',
    branchId: 'branch-4',
    branchName: 'Pet World Green Valley',
    designation: 'Sales Staff',
    role: 'SALES_STAFF',
    joiningDate: '2023-09-01',
    basicSalary: 21000,
    status: 'ACTIVE',
    username: 'anjali_b4',
  },

  // Branch 5 (Juhu)
  {
    id: 'staff-14',
    staffCode: 'STF-B05-01',
    name: 'Karan Malhotra',
    avatarType: 'dog',
    phone: '+91 98450 11998',
    email: 'karan.m@petworld.co.in',
    address: 'Gulmohar Cross Rd 10, Juhu, Mumbai',
    branchId: 'branch-5',
    branchName: 'Pet World Coastal Bay',
    designation: 'Branch Manager',
    role: 'BRANCH_MANAGER',
    joiningDate: '2023-06-12',
    basicSalary: 54000,
    status: 'ACTIVE',
    username: 'karan_b5',
  },
  {
    id: 'staff-15',
    staffCode: 'STF-B05-02',
    name: 'Divya Shenoy',
    avatarType: 'cat',
    phone: '+91 98451 22009',
    email: 'divya.s@petworld.co.in',
    address: 'Vile Parle West, Mumbai',
    branchId: 'branch-5',
    branchName: 'Pet World Coastal Bay',
    designation: 'Cashier',
    role: 'CASHIER',
    joiningDate: '2023-07-01',
    basicSalary: 28000,
    status: 'ACTIVE',
    username: 'divya_b5',
  },
  {
    id: 'staff-16',
    staffCode: 'STF-B05-03',
    name: 'Manish Pandey',
    avatarType: 'fish',
    phone: '+91 98452 33110',
    email: 'manish.p@petworld.co.in',
    address: 'JVPD Scheme, Juhu, Mumbai',
    branchId: 'branch-5',
    branchName: 'Pet World Coastal Bay',
    designation: 'Sales Staff',
    role: 'SALES_STAFF',
    joiningDate: '2024-02-15',
    basicSalary: 21000,
    status: 'ACTIVE',
    username: 'manish_b5',
  },

  // Branch 6 (Thane)
  {
    id: 'staff-17',
    staffCode: 'STF-B06-01',
    name: 'Sunita Patil',
    avatarType: 'bird',
    phone: '+91 98700 88771',
    email: 'sunita.patil@petworld.co.in',
    address: 'Majiwada Junction, Thane West',
    branchId: 'branch-6',
    branchName: 'Pet World Express Hub',
    designation: 'Branch Manager',
    role: 'BRANCH_MANAGER',
    joiningDate: '2024-01-18',
    basicSalary: 50000,
    status: 'ACTIVE',
    username: 'sunita_b6',
  },
  {
    id: 'staff-18',
    staffCode: 'STF-B06-02',
    name: 'Ramesh Sawant',
    avatarType: 'dog',
    phone: '+91 98701 99882',
    email: 'ramesh.s@petworld.co.in',
    address: 'Ghodbunder Road, Thane West',
    branchId: 'branch-6',
    branchName: 'Pet World Express Hub',
    designation: 'Cashier',
    role: 'CASHIER',
    joiningDate: '2024-02-01',
    basicSalary: 26000,
    status: 'ACTIVE',
    username: 'ramesh_b6',
  },
  {
    id: 'staff-19',
    staffCode: 'STF-B06-03',
    name: 'Aditi Joshi',
    avatarType: 'rabbit',
    phone: '+91 98702 11223',
    email: 'aditi.j@petworld.co.in',
    address: 'Naupada, Thane West',
    branchId: 'branch-6',
    branchName: 'Pet World Express Hub',
    designation: 'Sales Staff',
    role: 'SALES_STAFF',
    joiningDate: '2024-04-10',
    basicSalary: 20000,
    status: 'ACTIVE',
    username: 'aditi_b6',
  },
  {
    id: 'staff-20',
    staffCode: 'STF-B06-04',
    name: 'Tanmay Kulkarni',
    avatarType: 'hamster',
    phone: '+91 98703 22334',
    email: 'tanmay.k@petworld.co.in',
    address: 'Wagle Estate, Thane West',
    branchId: 'branch-6',
    branchName: 'Pet World Express Hub',
    designation: 'Sales Staff',
    role: 'SALES_STAFF',
    joiningDate: '2024-06-01',
    basicSalary: 20000,
    status: 'ACTIVE',
    username: 'tanmay_b6',
  },
];

// Super Admin User
export const OWNER_USER: User = {
  id: 'usr-owner-001',
  username: 'owner',
  name: 'Vikram Singhania',
  email: 'owner@petworld.co.in',
  phone: '+91 98200 11000',
  role: 'OWNER',
  avatarType: 'dog',
  designation: 'Founder & Super Admin',
  status: 'ACTIVE',
};

// Initial Purchases & Allocations
export const INITIAL_PURCHASES: Purchase[] = [
  {
    id: 'pur-001',
    purchaseNumber: 'PUR-2026-00001',
    company: 'Royal Canin',
    supplierId: 'sup-1',
    supplierName: 'Royal Canin India Pvt Ltd',
    supplierInvoiceNumber: 'RC-INV-99214',
    purchaseDate: '2026-08-25',
    paymentStatus: 'PAID',
    paymentMethod: 'BANK_TRANSFER',
    items: [
      {
        productId: 'prod-001',
        productName: 'Royal Canin Maxi Adult Dog Food 15kg',
        sku: 'DF-RC-001',
        company: 'Royal Canin',
        brand: 'Royal Canin',
        quantity: 100,
        purchasePrice: 6200,
        taxPercent: 18,
        discount: 0,
        total: 731600,
      },
    ],
    subtotal: 620000,
    taxAmount: 111600,
    discountAmount: 0,
    grandTotal: 731600,
    notes: 'Central Bulk Monsoon Stock for all 6 Mumbai stores',
    allocatedStatus: 'FULLY_ALLOCATED',
    createdAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'pur-002',
    purchaseNumber: 'PUR-2026-00002',
    company: 'Pedigree (Mars Petcare)',
    supplierId: 'sup-2',
    supplierName: 'Mars Petcare India',
    supplierInvoiceNumber: 'MARS-WRH-4412',
    purchaseDate: '2026-08-28',
    paymentStatus: 'PAID',
    paymentMethod: 'BANK_TRANSFER',
    items: [
      {
        productId: 'prod-003',
        productName: 'Pedigree Adult Chicken & Vegetables 10kg',
        sku: 'DF-PED-003',
        company: 'Pedigree (Mars Petcare)',
        brand: 'Pedigree',
        quantity: 120,
        purchasePrice: 1650,
        taxPercent: 18,
        discount: 5000,
        total: 227740,
      },
      {
        productId: 'prod-015',
        productName: 'Whiskas Ocean Fish Adult Cat Food 7kg',
        sku: 'CF-WHI-015',
        company: 'Whiskas (Mars Petcare)',
        brand: 'Whiskas',
        quantity: 80,
        purchasePrice: 1550,
        taxPercent: 18,
        discount: 3000,
        total: 142780,
      },
    ],
    subtotal: 322000,
    taxAmount: 57960,
    discountAmount: 8000,
    grandTotal: 371960,
    notes: 'Commercial monthly pet food procurement',
    allocatedStatus: 'FULLY_ALLOCATED',
    createdAt: '2026-08-28T11:30:00Z',
  },
  {
    id: 'pur-003',
    purchaseNumber: 'PUR-2026-00003',
    company: 'Pet Passion Import & Distribution Hub',
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    supplierInvoiceNumber: 'PPI-INV-7731',
    purchaseDate: '2026-09-02',
    paymentStatus: 'PAID',
    paymentMethod: 'BANK_TRANSFER',
    items: [
      {
        productId: 'prod-047',
        productName: 'KONG Classic Durable Natural Rubber Dog Toy (Large)',
        sku: 'TY-KON-047',
        company: 'KONG Company',
        brand: 'KONG',
        quantity: 60,
        purchasePrice: 780,
        taxPercent: 18,
        discount: 0,
        total: 55224,
      },
      {
        productId: 'prod-063',
        productName: 'Bedsure Orthopedic Memory Foam Dog Sofa Bed Large (Grey)',
        sku: 'BM-BED-063',
        company: 'Bedsure Pet',
        brand: 'Bedsure',
        quantity: 30,
        purchasePrice: 2400,
        taxPercent: 18,
        discount: 2000,
        total: 82600,
      },
    ],
    subtotal: 118800,
    taxAmount: 21384,
    discountAmount: 2000,
    grandTotal: 138184,
    notes: 'Premium imported toys & orthopedic beds replenishment',
    allocatedStatus: 'PARTIALLY_ALLOCATED',
    createdAt: '2026-09-02T14:15:00Z',
  },
];

export const INITIAL_PURCHASE_BILLS: PurchaseBill[] = [
  {
    id: 'bill-001',
    billNumber: 'BILL-2026-001',
    purchaseId: 'pur-001',
    supplierId: 'sup-1',
    supplierName: 'Royal Canin India Pvt Ltd',
    invoiceDate: '2026-08-25',
    invoiceAmount: 731600,
    paymentStatus: 'PAID',
    fileName: 'RC_TaxInvoice_99214.pdf',
    notes: 'Original stamped invoice received with consignment at central hub.',
  },
  {
    id: 'bill-002',
    billNumber: 'BILL-2026-002',
    purchaseId: 'pur-002',
    supplierId: 'sup-2',
    supplierName: 'Mars Petcare India',
    invoiceDate: '2026-08-28',
    invoiceAmount: 371960,
    paymentStatus: 'PAID',
    fileName: 'MarsPet_TaxInvoice_4412.pdf',
    notes: 'Paid via HDFC Bank NEFT ref #HDFC0098124.',
  },
  {
    id: 'bill-003',
    billNumber: 'BILL-2026-003',
    purchaseId: 'pur-003',
    supplierId: 'sup-4',
    supplierName: 'Pet Passion Import & Distribution Hub',
    invoiceDate: '2026-09-02',
    invoiceAmount: 138184,
    paymentStatus: 'PAID',
    fileName: 'PetPassion_Bill_7731.pdf',
    notes: 'Partial stock allocated to B1 & B2, balance in central hub.',
  },
];

export const INITIAL_ALLOCATIONS: PurchaseAllocationRecord[] = [
  {
    id: 'alloc-001',
    purchaseId: 'pur-001',
    purchaseNumber: 'PUR-2026-00001',
    productId: 'prod-001',
    productName: 'Royal Canin Maxi Adult Dog Food 15kg',
    sku: 'DF-RC-001',
    totalPurchased: 100,
    allocations: [
      { branchId: 'branch-1', branchName: 'Pet World Downtown Flagship', allocatedQuantity: 20, previousStock: 5, newStock: 25 },
      { branchId: 'branch-2', branchName: 'Pet World Westside Mall', allocatedQuantity: 15, previousStock: 3, newStock: 18 },
      { branchId: 'branch-3', branchName: 'Pet World Suburban Plaza', allocatedQuantity: 25, previousStock: 15, newStock: 40 },
      { branchId: 'branch-4', branchName: 'Pet World Green Valley', allocatedQuantity: 10, previousStock: 2, newStock: 12 },
      { branchId: 'branch-5', branchName: 'Pet World Coastal Bay', allocatedQuantity: 20, previousStock: 11, newStock: 31 },
      { branchId: 'branch-6', branchName: 'Pet World Express Hub', allocatedQuantity: 10, previousStock: 10, newStock: 20 },
    ],
    allocatedBy: 'Vikram Singhania (Owner)',
    date: '2026-08-25',
    time: '11:45:00 AM',
    timestamp: 1787658300000,
    notes: 'Distributed to all 6 branches based on footfall analysis',
  },
];

export const INITIAL_STOCK_MOVEMENTS: StockMovement[] = [
  {
    id: 'sm-001',
    productId: 'prod-001',
    productName: 'Royal Canin Maxi Adult Dog Food 15kg',
    sku: 'DF-RC-001',
    branchId: 'branch-1',
    branchName: 'Pet World Downtown Flagship',
    previousQuantity: 5,
    quantityAdded: 20,
    quantityRemoved: 0,
    newQuantity: 25,
    operationType: 'STOCK ADDED',
    reason: 'Central purchase stock allocation',
    referenceNumber: 'PUR-2026-00001',
    purchaseBillNumber: 'BILL-2026-001',
    userName: 'Vikram Singhania',
    userRole: 'OWNER',
    date: '2026-08-25',
    time: '11:45:10 AM',
    timestamp: 1787658310000,
  },
  {
    id: 'sm-002',
    productId: 'prod-001',
    productName: 'Royal Canin Maxi Adult Dog Food 15kg',
    sku: 'DF-RC-001',
    branchId: 'branch-3',
    branchName: 'Pet World Suburban Plaza',
    previousQuantity: 15,
    quantityAdded: 25,
    quantityRemoved: 0,
    newQuantity: 40,
    operationType: 'STOCK ADDED',
    reason: 'Central purchase stock allocation',
    referenceNumber: 'PUR-2026-00001',
    purchaseBillNumber: 'BILL-2026-001',
    userName: 'Vikram Singhania',
    userRole: 'OWNER',
    date: '2026-08-25',
    time: '11:45:25 AM',
    timestamp: 1787658325000,
  },
  {
    id: 'sm-003',
    productId: 'prod-001',
    productName: 'Royal Canin Maxi Adult Dog Food 15kg',
    sku: 'DF-RC-001',
    branchId: 'branch-2',
    branchName: 'Pet World Westside Mall',
    previousQuantity: 20,
    quantityAdded: 0,
    quantityRemoved: 2,
    newQuantity: 18,
    operationType: 'STOCK SOLD',
    reason: 'Retail Counter Sale',
    referenceNumber: 'PW-SAL-2026-00012',
    userName: 'Kavita Menon',
    userRole: 'CASHIER',
    date: '2026-09-05',
    time: '03:15:40 PM',
    timestamp: 1788621340000,
  },
];

export const INITIAL_SALES: Sale[] = [
  {
    id: 'sal-001',
    invoiceNumber: 'PW-SAL-2026-00012',
    branchId: 'branch-2',
    branchName: 'Pet World Westside Mall',
    branchAddress: 'Ground Floor, Galleria Arcade, Linking Road, Bandra West',
    branchPhone: '+91 22 2640 8822',
    staffId: 'staff-06',
    staffName: 'Kavita Menon',
    customerName: 'Aditya Kapoor',
    customerPhone: '+91 98200 45451',
    items: [
      {
        productId: 'prod-001',
        productName: 'Royal Canin Maxi Adult Dog Food 15kg',
        sku: 'DF-RC-001',
        unit: 'packet',
        quantity: 2,
        unitPrice: 7990,
        discount: 200,
        taxPercent: 18,
        taxAmount: 2404.78,
        lineTotal: 15780,
      },
      {
        productId: 'prod-039',
        productName: 'JerHigh Milky Dog Sticks Real Chicken 70g',
        sku: 'TR-JER-039',
        unit: 'packet',
        quantity: 3,
        unitPrice: 165,
        discount: 0,
        taxPercent: 18,
        taxAmount: 75.5,
        lineTotal: 495,
      },
    ],
    subtotal: 13794.72,
    discountTotal: 200,
    taxTotal: 2480.28,
    grandTotal: 16275,
    paymentMethod: 'UPI',
    status: 'COMPLETED',
    date: '2026-09-05',
    time: '03:15:40 PM',
    timestamp: 1788621340000,
  },
  {
    id: 'sal-002',
    invoiceNumber: 'PW-SAL-2026-00013',
    branchId: 'branch-1',
    branchName: 'Pet World Downtown Flagship',
    branchAddress: '14/B, Colaba Causeway, Near Regal Cinema',
    branchPhone: '+91 22 2202 1144',
    staffId: 'staff-02',
    staffName: 'Deepak Kamble',
    customerName: 'Zoya Merchant',
    customerPhone: '+91 98211 77889',
    items: [
      {
        productId: 'prod-013',
        productName: 'Royal Canin Kitten Second Age 4kg',
        sku: 'CF-RC-013',
        unit: 'packet',
        quantity: 1,
        unitPrice: 3350,
        discount: 50,
        taxPercent: 18,
        taxAmount: 503.39,
        lineTotal: 3300,
      },
      {
        productId: 'prod-041',
        productName: 'Temptations Tasty Chicken Crunchy Cat Treats 85g',
        sku: 'TR-TEM-041',
        unit: 'packet',
        quantity: 2,
        unitPrice: 180,
        discount: 0,
        taxPercent: 18,
        taxAmount: 54.91,
        lineTotal: 360,
      },
      {
        productId: 'prod-088',
        productName: 'Hooded Enclosed Cat Litter Box with Carbon Filter & Scoop',
        sku: 'AC-LIT-088',
        unit: 'piece',
        quantity: 1,
        unitPrice: 1890,
        discount: 90,
        taxPercent: 18,
        taxAmount: 274.58,
        lineTotal: 1800,
      },
    ],
    subtotal: 4627.12,
    discountTotal: 140,
    taxTotal: 832.88,
    grandTotal: 5460,
    paymentMethod: 'CARD',
    status: 'COMPLETED',
    date: '2026-09-05',
    time: '05:40:12 PM',
    timestamp: 1788630012000,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-03',
    type: 'LARGE_PURCHASE',
    title: 'New Bulk Purchase Inward',
    message: 'Purchase PUR-2026-00003 registered with Pet Passion Hub for ₹1,38,184.',
    timestamp: Date.now() - 3600000 * 24,
    date: '2026-09-05',
    time: '11:00 AM',
    isRead: true,
    referenceId: 'pur-003',
  },
  {
    id: 'notif-04',
    type: 'ATTENDANCE_ALERT',
    title: 'Late Check-in Logged',
    message: 'Rohan Naik (Branch 1 - Colaba) checked in at 10:45 AM (Shift began at 10:00 AM).',
    branchId: 'branch-1',
    branchName: 'Pet World Downtown Flagship',
    timestamp: Date.now() - 3600000 * 2,
    date: '2026-09-06',
    time: '10:45 AM',
    isRead: false,
  },
];
